export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCTBY_ID_SUCCESS";
export const FIND_PRODUCT_BY_ID_FIALURE = "FIND_PRODUCTBY_ID_FIALURE";
export const FIND_PRODUCT_BY_ID_REQUEST = "FIND_PRODUCTBY_ID_REQUEST";

export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCT_BY_CATEGORY_SUCCESS";
export const FIND_PRODUCTS_FIALURE = "FIND_PRODUCT_BY_CATEGORY_FIALURE";
export const FIND_PRODUCTS_REQUEST = "FIND_PRODUCT_BY_CATEGORY_REQUEST"

