export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILURE = "CREATE_PAYMENT_FAILURE";

export const UPDATE_PAYEMENT_REQUEST = "UPDATE_PAYEMENT_REQUEST";
export const UPDATE_PAYEMENT_SUCCESSS = "UPDATE_PAYEMENT_SUCCESS";
export const UPDATE_PAYEMENT_FAILURE = "UPDATE_PAYEMENT_FAILURE"